-- Add the LGU franchise to the verification document types.
--
-- The original enum (20260728090400_driver_documents.sql) has drivers_license,
-- or_cr, toda_membership, barangay_clearance, and vehicle_photo -- but no slot
-- for the franchise itself. In Calamba a tricycle operates under an MTOP
-- (Motorized Tricycle Operator's Permit) issued by the City; or_cr is the
-- vehicle's registration with the LTO, which is a different document proving
-- a different thing. Treating or_cr as though it covered the franchise would
-- be visibly wrong to any panelist who works with the permit.
--
-- ALONE IN ITS OWN MIGRATION ON PURPOSE
--
-- PostgreSQL cannot *use* a new enum value in the same transaction that adds
-- it. Anything referencing 'mtop_franchise' -- the required-document list,
-- seed rows, tests -- must therefore live in a later migration than this one.
--
-- PROVISIONAL: whether these four are the documents Calamba actually requires
-- is unconfirmed. See docs/CLIENT_MEETING_QUESTIONS.md question B1, and
-- .pipeline/specs.md §10 open question 1. The required list is deliberately
-- defined in exactly one function so correcting it is a one-line change.

alter type public.document_type add value if not exists 'mtop_franchise';
